spring.application.name=HackFusion

# Database Connection Settings

spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:4000}/${PGDATABASE:hackfusion}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:varshita_123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
TelegramBot=8462437080:AAHJHAg31res_Rdf5lntNbaeJev-Xa3tXW4

spring.ai.google.genai.project-id=${GOOGLE_GENAI_PROJECT_ID}
spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}

# Optional: Specify the model (default is usually gemini-1.5-flash)
<<<<<<< Updated upstream
spring.ai.google.genai.chat.options.model=gemini-1.5-flash
spring.jackson.serialization.fail-on-empty-beans=false
=======
spring.ai.google.genai.chat.options.model=gemini-1.5-flash
>>>>>>> Stashed changes
