spring.application.name=HackFusion

# Database Connection Settings

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
TelegramBot=${TelegramBot}

spring.ai.google.genai.project-id=${GOOGLE_GENAI_PROJECT_ID}
spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}

# Optional: Specify the model (default is usually gemini-1.5-flash)
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
management.endpoints.web.exposure.include=*
cloudinary.cloud_name=${cloud_name}
cloudinary.api_key=${api_key}
cloudinary.api_secret=${api_secret}
spring.jackson.serialization.fail-on-empty-beans=false
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
pinata.api.url=https://api.pinata.cloud/pinning/pinFileToIPFS
pinata.api.jwt=${PINATA_JWT}
logging.level.com.shivsharan.HackFusion=DEBUG