spring.application.name=HackFusion

# Database Connection Settings

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
TelegramBot=${TelegramBot}

spring.ai.google.genai.project-id=${GOOGLE_GENAI_PROJECT_ID}
spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}

# Optional: Specify the model (default is usually gemini-1.5-flash)
spring.ai.google.genai.chat.options.model=gemini-1.5-flash-lastest
management.endpoints.web.exposure.include=*