spring.application.name=HackFusion

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
TelegramBot=8462437080:AAHJHAg31res_Rdf5lntNbaeJev-Xa3tXW4

